Controllers/API/ReviewController.cs
using AIIntegrations.Models;
using AIIntegrations.Models.Dtos;
using AIIntegrations.Services.EmailService;
using AIIntegrations.Services.ReviewService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace AIIntegrations.Controllers.API;

[ApiController]
[Route("api/review")]
public class ReviewController : ControllerBase
{
    private readonly IReviewService _reviewService;
    private readonly IEmailService _emailService;
    private readonly IWebHostEnvironment _env;
    
    public ReviewController(IReviewService reviewService, IEmailService emailService, IWebHostEnvironment env)
    {
        _reviewService = reviewService;
        _emailService = emailService;
        _env = env;
    }
    
    [HttpPost]
    [Route("send")]
    public async Task<IActionResult> SendReview(ReviewModel review)
    {
        var html = _emailService.CreateBody(review);
        
        var request = new EmailDto
        {
            Subject = "Заявка",
            Body = html
        };

        await _reviewService.SaveNewReviewAsync(review);
        
        if (_env.IsDevelopment()) return Ok();
        
        await _emailService.SendEmailAsync(request);
        return Ok();
    }
    
    [HttpGet]
    [Route("approved")]
    public async Task<IActionResult> GetReviews()
    {
        return Ok(await _reviewService.GetApprovedReviewsAsync());
    }
    
    [HttpGet]
    [Route("all")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> GetAllReviews()
    {
        return Ok(await _reviewService.GetAllReviewsAsync());
    }
    
    [HttpPut]
    [Route("approve/{id:int}")]
    [Authorize(Roles = "Admin")]
    public async Task<IActionResult> ApproveReview(int id)
    {
        var result = await _reviewService.ApproveReviewAsync(id);

        if (result)
        {
            return Ok();
        }

        return BadRequest();
    }
}

Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace AIIntegrations.Controllers;

public class UserController : Controller
{
    // GET
    public IActionResult Login()
    {
        return View();
    }

    public IActionResult Register()
    {
        return View();
    }
}

Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
	<title>@ViewData["Title"] - Admin Panel</title>
	<environment include="Development">
		<link rel="stylesheet" href="~/css/admin.css" asp-append-version="true">
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="/css/admin-bundle.css" asp-append-version="true">
	</environment>
	@await RenderSectionAsync("Styles", required: false)
	<environment exclude="Development">
		@* important js, maybe analytics *@
	</environment>
</head>
<body>
<environment exclude="Development">
	<noscript>
		@* no script part of important, maybe analytics *@
	</noscript>
</environment>
<environment include="Development">
	<div id="development-mode"></div>
</environment>
<header>
	<nav>
		<ul>
			@* <li> *@
			@* 	<a asp-area="" asp-controller="Home" asp-action="Index">Home</a> *@
			@* </li> *@
			@* <li> *@
			@* 	<a asp-area="" asp-controller="Review" asp-action="Index">Review</a> *@
			@* </li> *@
			@* <li> *@
			@* 	<a asp-area="" asp-controller="User" asp-action="Login">User Login</a> *@
			@* </li> *@
			@* <li> *@
			@* 	<a asp-area="" asp-controller="User" asp-action="Register">User Register</a> *@
			@* </li> *@
		</ul>
	</nav>
	<br>
    <br>
    <br>
    <button class="logout">Logout</button>
    <br>
    <br>
    <br>
</header>

<br>
<br>
<br>

<main>
	@RenderBody()
</main>

<br>
<br>
<br>

<footer>
	<div>
		&copy; 2023 - AIIntegrations Admin Panel
	</div>
</footer>
<div class="overlay" id="loader">
	@* place loader html here *@
</div>
<div class="overlay" id="overlay">
	@* <div class="modal" id="application"> *@
	@* 	<form class="application-form"> *@
	@* 		<span class="close-m" title="Закрыть">&times;</span> *@
	@* 		<h2>Оставьте заявку</h2> *@
	@* 		<div>Оставьте заявку, и мы перезвоним Вам в ближайшее время</div> *@
	@* 		<div> *@
	@* 			<input placeholder="Введите имя" type="text" name="name"> *@
	@* 		</div> *@
	@* 		<div> *@
	@* 			<input placeholder="Введите номер" type="tel" name="phone"> *@
	@* 		</div> *@
	@* 		<p>*Отправляя заявку, Вы потверждаете согласие согласие на обработку введенных персональных данных</p> *@
	@* 		<div class="validation"></div> *@
	@* 		<button type="submit">Оставить заявку</button> *@
	@* 	</form> *@
	@* </div> *@
	@* <div class="modal" id="application-success"> *@
	@* 	<div> *@
	@* 		Заявка отправлена *@
	@* 	</div> *@
	@* 	<div> *@
	@* 		Совсем скоро мы Вам позвоним *@
	@* 	</div> *@
	@* </div> *@
	@* <div class="modal" id="application-error"> *@
	@* 	<div> *@
	@* 		Что-то пошло не так *@
	@* 	</div> *@
	@* 	<div> *@
	@* 		Попробуйте позже пожалуйста или позвоните нам <a href="tel:+0000000">+0000000</a> *@
	@* 	</div> *@
	@* </div> *@
	@* <div class="modal" id="review-success"> *@
	@* 	<div> *@
	@* 		Ваш отзыв отправлен на модерацию и в скором времени будет размещен на сайте. *@
	@* 	</div> *@
	@* 	<div> *@
	@* 		Спасибо Вам за обратную связь! *@
	@* 	</div> *@
	@* </div> *@
	@* <div class="modal" id="review-error"> *@
	@* 	<div> *@
	@* 		Что-то пошло не так *@
	@* 	</div> *@
	@* 	<div> *@
	@* 		Попробуйте позже пожалуйста или позвоните нам <a href="tel:+0000000">+0000000</a> *@
	@* 	</div> *@
	@* </div> *@
</div>
<environment include="Development">
	<script src="~/js/phone-mask.js" asp-append-version="true"></script>
	<script src="~/js/api-request.js" asp-append-version="true"></script>
	<script src="~/js/loader.js" asp-append-version="true"></script>
	<script src="~/js/modal.js" asp-append-version="true"></script>
	<script src="~/js/helpers.js" asp-append-version="true"></script>
	<script src="~/js/form-request.js" asp-append-version="true"></script>
	<script src="~/js/admin/layout.js" asp-append-version="true"></script>
</environment>
<environment exclude="Development">
	<script src="~/js/admin-layout-bundle.js" asp-append-version="true"></script>
</environment>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>